name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nix
        uses: cachix/install-nix-action@v17
      - name: Build with Nix
        run: nix build .#docker
