name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ] #, macos-13, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"
      - name: checkout
        uses: actions/checkout@v5
      - name: Build go app + docker image using Nix
        shell: bash
        run: |
          nix build .#docker
          docker load < result
          docker image ls
