name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ] #, macos-13, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Nix
        uses: cachix/install-nix-action@v31
      - name: checkout
        uses: actions/checkout@v4
      - name: Build go app + docker image using Nix
        run: nix build .#docker
      - name: load image
        run: docker load < result
      - name: check images
        run: docker image ls
